ARG version
FROM almalinux:${version}
CMD ["ping", "google.com"]
# ARG username
# RUN adduser $username
# USER $username
# ARG COURSE
# ENV COURSE=${COURSE}
# RUN echo "COURSE:${COURSE}"
# ENTRYPOINT ["ping", "google.com"]
# RUN yum install nginx -y
# WORKDIR /tmp
# RUN echo "hari KRISHNA" > file.txt
# ENV username="hari"
# ADD https://raw.githubusercontent.com/daws-76s/notes/master/session-01.txt /tmp/
# RUN rm -rf /usr/share/nginx/html/index.html
# COPY index.html /usr/share/nginx/html/
# LABEL NAME="HARI KRISHNA"\
#       COURSE="AWS DEVOPS"
# EXPOSE 80/tcp